### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by VovaTimoshevskiy** [VovaTimoshevskiy/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by VovaTimoshevskiy** [comment]
Scientist, inventor, genius. Not affiliated with Adult Swim because b-bburp I don't respect them. Wubba lubba dub dub

**Comment by VovaTimosh** [comment]
<h2>Resume</h2>
<p>Scientist, inventor, genius. Not affiliated with Adult Swim because b-bburp I don't respect them. Wubba lubba dub dub</p>
