### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by VovaTimoshevskiy** [VovaTimoshevskiy/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.
Скласти таймлайн

**Comment by VovaTimosh** [comment]
https://twitter.com/c137ricksanchez
https://www.instagram.com/rickandmorty/
