### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by VovaTimoshevskiy** [VovaTimoshevskiy/homepage#8]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by VovaTimosh** [comment]
Rick's strengths:

Persistence, Persuasive, Systematic, Mission oriented

Weaknesses:

Uncommitted... but compensated by the fact that in little time he can accomplish a great many tasks or 1 task with exceptional marks

Experience/Skills/Study:

Rick is surprisingly competent when he sets his mind to it. You'll find that even though he is viewed upon negatively, setting your sympathy for his detractors aside, it is very clear that Rick is advanced "beyond his time" in science and engineering. If he really wanted to, he could cure cancer... rewrite space / time.
